title    GregorOpmannOS Live (%ARCH%, UEFI) with speech
sort-key 02
linux    /gregor0/boot/%ARCH%/vmlinuz-linux
initrd   /gregor0/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=gregor0 archisolabel=GREGORO_OS accessibility=on copytoram=y
